#!/usr/bin/env -S ruby -E UTF-8:UTF-8

if ARGV.length != 3
  puts "Usage: #{$PROGRAM_NAME} github_token tracker_token revision_range"
  exit(1)
end

github_token, tracker_token, revision_range = ARGV

require 'bundler/inline'
gemfile do
  gem 'sonar-ci-tools', git: "https://#{github_token}:x-oauth-basic@github.com/nhsx/sonar-ios", glob: 'ci/ruby/sonar-ci-tools.gemspec'
end
puts 'Gems loaded'
puts

require 'generates_release_notes'
include GeneratesReleaseNotes

puts "generating release report for #{revision_range}"
puts

io = StringIO.new
generate_release_notes(
    io: io,
    tracker_token: tracker_token,
    commits: revision_range,
)

release_notes = io.string
puts "Generated release notes"
puts

puts release_notes
puts

puts "Setting action output"
escaped = release_notes.gsub(
  /[\n\r%]/,
  "\n" => '%0A',
  '%' => '%25',
  "\r" => '%0D'
);

puts "::set-output name=release_notes::#{escaped}"
